// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/api/v1/rp_api_platform.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum RPPlatform: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case apple // = 1
  case android // = 2
  case flutter // = 3
  case embedded // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .apple
    case 2: self = .android
    case 3: self = .flutter
    case 4: self = .embedded
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .apple: return 1
    case .android: return 2
    case .flutter: return 3
    case .embedded: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPPlatform] = [
    .unspecified,
    .apple,
    .android,
    .flutter,
    .embedded,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension RPPlatform: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_PLATFORM_UNSPECIFIED\0\u{1}RP_PLATFORM_APPLE\0\u{1}RP_PLATFORM_ANDROID\0\u{1}RP_PLATFORM_FLUTTER\0\u{1}RP_PLATFORM_EMBEDDED\0")
}
