// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/api/v1/rp_api_health_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - proto.renderprotocol.api.v1.RPHealthService

/// Namespace containing generated types for the "proto.renderprotocol.api.v1.RPHealthService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum RPHealthService: Sendable {
    /// Service descriptor for the "proto.renderprotocol.api.v1.RPHealthService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPHealthService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "RPHealthCheck" metadata.
        public enum RPHealthCheck: Sendable {
            /// Request type for "RPHealthCheck".
            public typealias Input = RPHealthCheckRequest
            /// Response type for "RPHealthCheck".
            public typealias Output = RPHealthCheckResponse
            /// Descriptor for "RPHealthCheck".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPHealthService"),
                method: "RPHealthCheck",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "proto.renderprotocol.api.v1.RPHealthService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            RPHealthCheck.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "proto.renderprotocol.api.v1.RPHealthService" service.
    public static let RPHealthService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPHealthService")
}

// MARK: proto.renderprotocol.api.v1.RPHealthService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHealthService {
    /// Streaming variant of the service protocol for the "proto.renderprotocol.api.v1.RPHealthService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "RPHealthCheck" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `RPHealthCheckRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RPHealthCheckResponse` messages.
        func rpHealthCheck(
            request: GRPCCore.StreamingServerRequest<RPHealthCheckRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RPHealthCheckResponse>
    }

    /// Service protocol for the "proto.renderprotocol.api.v1.RPHealthService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: RPHealthService.StreamingServiceProtocol {
        /// Handle the "RPHealthCheck" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPHealthCheckRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `RPHealthCheckResponse` message.
        func rpHealthCheck(
            request: GRPCCore.ServerRequest<RPHealthCheckRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<RPHealthCheckResponse>
    }

    /// Simple service protocol for the "proto.renderprotocol.api.v1.RPHealthService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: RPHealthService.ServiceProtocol {
        /// Handle the "RPHealthCheck" method.
        ///
        /// - Parameters:
        ///   - request: A `RPHealthCheckRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `RPHealthCheckResponse` to respond with.
        func rpHealthCheck(
            request: RPHealthCheckRequest,
            context: GRPCCore.ServerContext
        ) async throws -> RPHealthCheckResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHealthService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: RPHealthService.Method.RPHealthCheck.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPHealthCheckRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<RPHealthCheckResponse>(),
            handler: { request, context in
                try await self.rpHealthCheck(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHealthService.ServiceProtocol {
    public func rpHealthCheck(
        request: GRPCCore.StreamingServerRequest<RPHealthCheckRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RPHealthCheckResponse> {
        let response = try await self.rpHealthCheck(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHealthService.SimpleServiceProtocol {
    public func rpHealthCheck(
        request: GRPCCore.ServerRequest<RPHealthCheckRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<RPHealthCheckResponse> {
        return GRPCCore.ServerResponse<RPHealthCheckResponse>(
            message: try await self.rpHealthCheck(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: proto.renderprotocol.api.v1.RPHealthService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHealthService {
    /// Generated client protocol for the "proto.renderprotocol.api.v1.RPHealthService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "RPHealthCheck" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPHealthCheckRequest` message.
        ///   - serializer: A serializer for `RPHealthCheckRequest` messages.
        ///   - deserializer: A deserializer for `RPHealthCheckResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func rpHealthCheck<Result>(
            request: GRPCCore.ClientRequest<RPHealthCheckRequest>,
            serializer: some GRPCCore.MessageSerializer<RPHealthCheckRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPHealthCheckResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPHealthCheckResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "proto.renderprotocol.api.v1.RPHealthService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "RPHealthCheck" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPHealthCheckRequest` message.
        ///   - serializer: A serializer for `RPHealthCheckRequest` messages.
        ///   - deserializer: A deserializer for `RPHealthCheckResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func rpHealthCheck<Result>(
            request: GRPCCore.ClientRequest<RPHealthCheckRequest>,
            serializer: some GRPCCore.MessageSerializer<RPHealthCheckRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPHealthCheckResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPHealthCheckResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RPHealthService.Method.RPHealthCheck.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHealthService.ClientProtocol {
    /// Call the "RPHealthCheck" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `RPHealthCheckRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpHealthCheck<Result>(
        request: GRPCCore.ClientRequest<RPHealthCheckRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPHealthCheckResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.rpHealthCheck(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<RPHealthCheckRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPHealthCheckResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHealthService.ClientProtocol {
    /// Call the "RPHealthCheck" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpHealthCheck<Result>(
        _ message: RPHealthCheckRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPHealthCheckResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<RPHealthCheckRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.rpHealthCheck(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}