// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/api/v1/rp_api_status.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum RPStatusCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Success
  case ok // = 1

  /// Client errors
  case invalidRequest // = 10
  case unauthorized // = 11
  case sessionExpired // = 12
  case notFound // = 13
  case rateLimited // = 14
  case versionMismatch // = 15

  /// Server errors
  case internalError // = 20
  case unavailable // = 21
  case timeout // = 22
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .ok
    case 10: self = .invalidRequest
    case 11: self = .unauthorized
    case 12: self = .sessionExpired
    case 13: self = .notFound
    case 14: self = .rateLimited
    case 15: self = .versionMismatch
    case 20: self = .internalError
    case 21: self = .unavailable
    case 22: self = .timeout
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .ok: return 1
    case .invalidRequest: return 10
    case .unauthorized: return 11
    case .sessionExpired: return 12
    case .notFound: return 13
    case .rateLimited: return 14
    case .versionMismatch: return 15
    case .internalError: return 20
    case .unavailable: return 21
    case .timeout: return 22
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPStatusCode] = [
    .unspecified,
    .ok,
    .invalidRequest,
    .unauthorized,
    .sessionExpired,
    .notFound,
    .rateLimited,
    .versionMismatch,
    .internalError,
    .unavailable,
    .timeout,
  ]

}

public struct RPStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: RPStatusCode = .unspecified

  public var message: String = String()

  public var details: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto.renderprotocol.api.v1"

extension RPStatusCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_STATUS_CODE_UNSPECIFIED\0\u{1}RP_STATUS_CODE_OK\0\u{2}\u{9}RP_STATUS_CODE_INVALID_REQUEST\0\u{1}RP_STATUS_CODE_UNAUTHORIZED\0\u{1}RP_STATUS_CODE_SESSION_EXPIRED\0\u{1}RP_STATUS_CODE_NOT_FOUND\0\u{1}RP_STATUS_CODE_RATE_LIMITED\0\u{1}RP_STATUS_CODE_VERSION_MISMATCH\0\u{2}\u{5}RP_STATUS_CODE_INTERNAL_ERROR\0\u{1}RP_STATUS_CODE_UNAVAILABLE\0\u{1}RP_STATUS_CODE_TIMEOUT\0")
}

extension RPStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0\u{1}details\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.details) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .unspecified {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.details.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.details, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPStatus, rhs: RPStatus) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.details != rhs.details {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
