// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/api/v1/rp_api_render_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - proto.renderprotocol.api.v1.RPRenderService

/// Namespace containing generated types for the "proto.renderprotocol.api.v1.RPRenderService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum RPRenderService: Sendable {
    /// Service descriptor for the "proto.renderprotocol.api.v1.RPRenderService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPRenderService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "RPFetchRenderTree" metadata.
        public enum RPFetchRenderTree: Sendable {
            /// Request type for "RPFetchRenderTree".
            public typealias Input = RPFetchRenderTreeRequest
            /// Response type for "RPFetchRenderTree".
            public typealias Output = RPFetchRenderTreeResponse
            /// Descriptor for "RPFetchRenderTree".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPRenderService"),
                method: "RPFetchRenderTree"
            )
        }
        /// Descriptors for all methods in the "proto.renderprotocol.api.v1.RPRenderService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            RPFetchRenderTree.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "proto.renderprotocol.api.v1.RPRenderService" service.
    public static let RPRenderService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPRenderService")
}

// MARK: proto.renderprotocol.api.v1.RPRenderService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPRenderService {
    /// Streaming variant of the service protocol for the "proto.renderprotocol.api.v1.RPRenderService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "RPFetchRenderTree" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `RPFetchRenderTreeRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RPFetchRenderTreeResponse` messages.
        func rpFetchRenderTree(
            request: GRPCCore.StreamingServerRequest<RPFetchRenderTreeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RPFetchRenderTreeResponse>
    }

    /// Service protocol for the "proto.renderprotocol.api.v1.RPRenderService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: RPRenderService.StreamingServiceProtocol {
        /// Handle the "RPFetchRenderTree" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPFetchRenderTreeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `RPFetchRenderTreeResponse` message.
        func rpFetchRenderTree(
            request: GRPCCore.ServerRequest<RPFetchRenderTreeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<RPFetchRenderTreeResponse>
    }

    /// Simple service protocol for the "proto.renderprotocol.api.v1.RPRenderService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: RPRenderService.ServiceProtocol {
        /// Handle the "RPFetchRenderTree" method.
        ///
        /// - Parameters:
        ///   - request: A `RPFetchRenderTreeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `RPFetchRenderTreeResponse` to respond with.
        func rpFetchRenderTree(
            request: RPFetchRenderTreeRequest,
            context: GRPCCore.ServerContext
        ) async throws -> RPFetchRenderTreeResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPRenderService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: RPRenderService.Method.RPFetchRenderTree.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPFetchRenderTreeRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<RPFetchRenderTreeResponse>(),
            handler: { request, context in
                try await self.rpFetchRenderTree(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPRenderService.ServiceProtocol {
    public func rpFetchRenderTree(
        request: GRPCCore.StreamingServerRequest<RPFetchRenderTreeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RPFetchRenderTreeResponse> {
        let response = try await self.rpFetchRenderTree(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPRenderService.SimpleServiceProtocol {
    public func rpFetchRenderTree(
        request: GRPCCore.ServerRequest<RPFetchRenderTreeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<RPFetchRenderTreeResponse> {
        return GRPCCore.ServerResponse<RPFetchRenderTreeResponse>(
            message: try await self.rpFetchRenderTree(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: proto.renderprotocol.api.v1.RPRenderService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPRenderService {
    /// Generated client protocol for the "proto.renderprotocol.api.v1.RPRenderService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "RPFetchRenderTree" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPFetchRenderTreeRequest` message.
        ///   - serializer: A serializer for `RPFetchRenderTreeRequest` messages.
        ///   - deserializer: A deserializer for `RPFetchRenderTreeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func rpFetchRenderTree<Result>(
            request: GRPCCore.ClientRequest<RPFetchRenderTreeRequest>,
            serializer: some GRPCCore.MessageSerializer<RPFetchRenderTreeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPFetchRenderTreeResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPFetchRenderTreeResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "proto.renderprotocol.api.v1.RPRenderService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "RPFetchRenderTree" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPFetchRenderTreeRequest` message.
        ///   - serializer: A serializer for `RPFetchRenderTreeRequest` messages.
        ///   - deserializer: A deserializer for `RPFetchRenderTreeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func rpFetchRenderTree<Result>(
            request: GRPCCore.ClientRequest<RPFetchRenderTreeRequest>,
            serializer: some GRPCCore.MessageSerializer<RPFetchRenderTreeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPFetchRenderTreeResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPFetchRenderTreeResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RPRenderService.Method.RPFetchRenderTree.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPRenderService.ClientProtocol {
    /// Call the "RPFetchRenderTree" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `RPFetchRenderTreeRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpFetchRenderTree<Result>(
        request: GRPCCore.ClientRequest<RPFetchRenderTreeRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPFetchRenderTreeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.rpFetchRenderTree(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<RPFetchRenderTreeRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPFetchRenderTreeResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPRenderService.ClientProtocol {
    /// Call the "RPFetchRenderTree" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpFetchRenderTree<Result>(
        _ message: RPFetchRenderTreeRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPFetchRenderTreeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<RPFetchRenderTreeRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.rpFetchRenderTree(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}