// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/api/v1/rp_api_event_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - proto.renderprotocol.api.v1.RPEventService

/// Namespace containing generated types for the "proto.renderprotocol.api.v1.RPEventService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum RPEventService: Sendable {
    /// Service descriptor for the "proto.renderprotocol.api.v1.RPEventService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPEventService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "RPSubmitEvent" metadata.
        public enum RPSubmitEvent: Sendable {
            /// Request type for "RPSubmitEvent".
            public typealias Input = RPSubmitEventRequest
            /// Response type for "RPSubmitEvent".
            public typealias Output = RPSubmitEventResponse
            /// Descriptor for "RPSubmitEvent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPEventService"),
                method: "RPSubmitEvent"
            )
        }
        /// Namespace for "RPSubmitBatchEvents" metadata.
        public enum RPSubmitBatchEvents: Sendable {
            /// Request type for "RPSubmitBatchEvents".
            public typealias Input = RPSubmitBatchEventsRequest
            /// Response type for "RPSubmitBatchEvents".
            public typealias Output = RPSubmitBatchEventsResponse
            /// Descriptor for "RPSubmitBatchEvents".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPEventService"),
                method: "RPSubmitBatchEvents"
            )
        }
        /// Descriptors for all methods in the "proto.renderprotocol.api.v1.RPEventService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            RPSubmitEvent.descriptor,
            RPSubmitBatchEvents.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "proto.renderprotocol.api.v1.RPEventService" service.
    public static let RPEventService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPEventService")
}

// MARK: proto.renderprotocol.api.v1.RPEventService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPEventService {
    /// Streaming variant of the service protocol for the "proto.renderprotocol.api.v1.RPEventService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "RPSubmitEvent" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `RPSubmitEventRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RPSubmitEventResponse` messages.
        func rpSubmitEvent(
            request: GRPCCore.StreamingServerRequest<RPSubmitEventRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RPSubmitEventResponse>

        /// Handle the "RPSubmitBatchEvents" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `RPSubmitBatchEventsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RPSubmitBatchEventsResponse` messages.
        func rpSubmitBatchEvents(
            request: GRPCCore.StreamingServerRequest<RPSubmitBatchEventsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RPSubmitBatchEventsResponse>
    }

    /// Service protocol for the "proto.renderprotocol.api.v1.RPEventService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: RPEventService.StreamingServiceProtocol {
        /// Handle the "RPSubmitEvent" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPSubmitEventRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `RPSubmitEventResponse` message.
        func rpSubmitEvent(
            request: GRPCCore.ServerRequest<RPSubmitEventRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<RPSubmitEventResponse>

        /// Handle the "RPSubmitBatchEvents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPSubmitBatchEventsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `RPSubmitBatchEventsResponse` message.
        func rpSubmitBatchEvents(
            request: GRPCCore.ServerRequest<RPSubmitBatchEventsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<RPSubmitBatchEventsResponse>
    }

    /// Simple service protocol for the "proto.renderprotocol.api.v1.RPEventService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: RPEventService.ServiceProtocol {
        /// Handle the "RPSubmitEvent" method.
        ///
        /// - Parameters:
        ///   - request: A `RPSubmitEventRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `RPSubmitEventResponse` to respond with.
        func rpSubmitEvent(
            request: RPSubmitEventRequest,
            context: GRPCCore.ServerContext
        ) async throws -> RPSubmitEventResponse

        /// Handle the "RPSubmitBatchEvents" method.
        ///
        /// - Parameters:
        ///   - request: A `RPSubmitBatchEventsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `RPSubmitBatchEventsResponse` to respond with.
        func rpSubmitBatchEvents(
            request: RPSubmitBatchEventsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> RPSubmitBatchEventsResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPEventService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: RPEventService.Method.RPSubmitEvent.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPSubmitEventRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<RPSubmitEventResponse>(),
            handler: { request, context in
                try await self.rpSubmitEvent(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: RPEventService.Method.RPSubmitBatchEvents.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPSubmitBatchEventsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<RPSubmitBatchEventsResponse>(),
            handler: { request, context in
                try await self.rpSubmitBatchEvents(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPEventService.ServiceProtocol {
    public func rpSubmitEvent(
        request: GRPCCore.StreamingServerRequest<RPSubmitEventRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RPSubmitEventResponse> {
        let response = try await self.rpSubmitEvent(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func rpSubmitBatchEvents(
        request: GRPCCore.StreamingServerRequest<RPSubmitBatchEventsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RPSubmitBatchEventsResponse> {
        let response = try await self.rpSubmitBatchEvents(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPEventService.SimpleServiceProtocol {
    public func rpSubmitEvent(
        request: GRPCCore.ServerRequest<RPSubmitEventRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<RPSubmitEventResponse> {
        return GRPCCore.ServerResponse<RPSubmitEventResponse>(
            message: try await self.rpSubmitEvent(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func rpSubmitBatchEvents(
        request: GRPCCore.ServerRequest<RPSubmitBatchEventsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<RPSubmitBatchEventsResponse> {
        return GRPCCore.ServerResponse<RPSubmitBatchEventsResponse>(
            message: try await self.rpSubmitBatchEvents(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: proto.renderprotocol.api.v1.RPEventService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPEventService {
    /// Generated client protocol for the "proto.renderprotocol.api.v1.RPEventService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "RPSubmitEvent" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPSubmitEventRequest` message.
        ///   - serializer: A serializer for `RPSubmitEventRequest` messages.
        ///   - deserializer: A deserializer for `RPSubmitEventResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func rpSubmitEvent<Result>(
            request: GRPCCore.ClientRequest<RPSubmitEventRequest>,
            serializer: some GRPCCore.MessageSerializer<RPSubmitEventRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPSubmitEventResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPSubmitEventResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RPSubmitBatchEvents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPSubmitBatchEventsRequest` message.
        ///   - serializer: A serializer for `RPSubmitBatchEventsRequest` messages.
        ///   - deserializer: A deserializer for `RPSubmitBatchEventsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func rpSubmitBatchEvents<Result>(
            request: GRPCCore.ClientRequest<RPSubmitBatchEventsRequest>,
            serializer: some GRPCCore.MessageSerializer<RPSubmitBatchEventsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPSubmitBatchEventsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPSubmitBatchEventsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "proto.renderprotocol.api.v1.RPEventService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "RPSubmitEvent" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPSubmitEventRequest` message.
        ///   - serializer: A serializer for `RPSubmitEventRequest` messages.
        ///   - deserializer: A deserializer for `RPSubmitEventResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func rpSubmitEvent<Result>(
            request: GRPCCore.ClientRequest<RPSubmitEventRequest>,
            serializer: some GRPCCore.MessageSerializer<RPSubmitEventRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPSubmitEventResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPSubmitEventResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RPEventService.Method.RPSubmitEvent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RPSubmitBatchEvents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPSubmitBatchEventsRequest` message.
        ///   - serializer: A serializer for `RPSubmitBatchEventsRequest` messages.
        ///   - deserializer: A deserializer for `RPSubmitBatchEventsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func rpSubmitBatchEvents<Result>(
            request: GRPCCore.ClientRequest<RPSubmitBatchEventsRequest>,
            serializer: some GRPCCore.MessageSerializer<RPSubmitBatchEventsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPSubmitBatchEventsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPSubmitBatchEventsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RPEventService.Method.RPSubmitBatchEvents.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPEventService.ClientProtocol {
    /// Call the "RPSubmitEvent" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `RPSubmitEventRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpSubmitEvent<Result>(
        request: GRPCCore.ClientRequest<RPSubmitEventRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPSubmitEventResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.rpSubmitEvent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<RPSubmitEventRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPSubmitEventResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RPSubmitBatchEvents" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `RPSubmitBatchEventsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpSubmitBatchEvents<Result>(
        request: GRPCCore.ClientRequest<RPSubmitBatchEventsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPSubmitBatchEventsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.rpSubmitBatchEvents(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<RPSubmitBatchEventsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPSubmitBatchEventsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPEventService.ClientProtocol {
    /// Call the "RPSubmitEvent" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpSubmitEvent<Result>(
        _ message: RPSubmitEventRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPSubmitEventResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<RPSubmitEventRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.rpSubmitEvent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RPSubmitBatchEvents" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpSubmitBatchEvents<Result>(
        _ message: RPSubmitBatchEventsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPSubmitBatchEventsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<RPSubmitBatchEventsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.rpSubmitBatchEvents(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}