// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/api/v1/rp_api_handshake_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - proto.renderprotocol.api.v1.RPHandshakeService

/// Namespace containing generated types for the "proto.renderprotocol.api.v1.RPHandshakeService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum RPHandshakeService: Sendable {
    /// Service descriptor for the "proto.renderprotocol.api.v1.RPHandshakeService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPHandshakeService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "RPInitiate" metadata.
        public enum RPInitiate: Sendable {
            /// Request type for "RPInitiate".
            public typealias Input = RPInitiateRequest
            /// Response type for "RPInitiate".
            public typealias Output = RPInitiateResponse
            /// Descriptor for "RPInitiate".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPHandshakeService"),
                method: "RPInitiate"
            )
        }
        /// Namespace for "RPRefreshSession" metadata.
        public enum RPRefreshSession: Sendable {
            /// Request type for "RPRefreshSession".
            public typealias Input = RPRefreshSessionRequest
            /// Response type for "RPRefreshSession".
            public typealias Output = RPRefreshSessionResponse
            /// Descriptor for "RPRefreshSession".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPHandshakeService"),
                method: "RPRefreshSession"
            )
        }
        /// Namespace for "RPEndSession" metadata.
        public enum RPEndSession: Sendable {
            /// Request type for "RPEndSession".
            public typealias Input = RPEndSessionRequest
            /// Response type for "RPEndSession".
            public typealias Output = RPEndSessionResponse
            /// Descriptor for "RPEndSession".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPHandshakeService"),
                method: "RPEndSession"
            )
        }
        /// Descriptors for all methods in the "proto.renderprotocol.api.v1.RPHandshakeService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            RPInitiate.descriptor,
            RPRefreshSession.descriptor,
            RPEndSession.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "proto.renderprotocol.api.v1.RPHandshakeService" service.
    public static let RPHandshakeService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.renderprotocol.api.v1.RPHandshakeService")
}

// MARK: proto.renderprotocol.api.v1.RPHandshakeService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHandshakeService {
    /// Streaming variant of the service protocol for the "proto.renderprotocol.api.v1.RPHandshakeService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "RPInitiate" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `RPInitiateRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RPInitiateResponse` messages.
        func rpInitiate(
            request: GRPCCore.StreamingServerRequest<RPInitiateRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RPInitiateResponse>

        /// Handle the "RPRefreshSession" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `RPRefreshSessionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RPRefreshSessionResponse` messages.
        func rpRefreshSession(
            request: GRPCCore.StreamingServerRequest<RPRefreshSessionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RPRefreshSessionResponse>

        /// Handle the "RPEndSession" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `RPEndSessionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RPEndSessionResponse` messages.
        func rpEndSession(
            request: GRPCCore.StreamingServerRequest<RPEndSessionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RPEndSessionResponse>
    }

    /// Service protocol for the "proto.renderprotocol.api.v1.RPHandshakeService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: RPHandshakeService.StreamingServiceProtocol {
        /// Handle the "RPInitiate" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPInitiateRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `RPInitiateResponse` message.
        func rpInitiate(
            request: GRPCCore.ServerRequest<RPInitiateRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<RPInitiateResponse>

        /// Handle the "RPRefreshSession" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPRefreshSessionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `RPRefreshSessionResponse` message.
        func rpRefreshSession(
            request: GRPCCore.ServerRequest<RPRefreshSessionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<RPRefreshSessionResponse>

        /// Handle the "RPEndSession" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPEndSessionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `RPEndSessionResponse` message.
        func rpEndSession(
            request: GRPCCore.ServerRequest<RPEndSessionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<RPEndSessionResponse>
    }

    /// Simple service protocol for the "proto.renderprotocol.api.v1.RPHandshakeService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: RPHandshakeService.ServiceProtocol {
        /// Handle the "RPInitiate" method.
        ///
        /// - Parameters:
        ///   - request: A `RPInitiateRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `RPInitiateResponse` to respond with.
        func rpInitiate(
            request: RPInitiateRequest,
            context: GRPCCore.ServerContext
        ) async throws -> RPInitiateResponse

        /// Handle the "RPRefreshSession" method.
        ///
        /// - Parameters:
        ///   - request: A `RPRefreshSessionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `RPRefreshSessionResponse` to respond with.
        func rpRefreshSession(
            request: RPRefreshSessionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> RPRefreshSessionResponse

        /// Handle the "RPEndSession" method.
        ///
        /// - Parameters:
        ///   - request: A `RPEndSessionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `RPEndSessionResponse` to respond with.
        func rpEndSession(
            request: RPEndSessionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> RPEndSessionResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHandshakeService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: RPHandshakeService.Method.RPInitiate.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPInitiateRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<RPInitiateResponse>(),
            handler: { request, context in
                try await self.rpInitiate(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: RPHandshakeService.Method.RPRefreshSession.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPRefreshSessionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<RPRefreshSessionResponse>(),
            handler: { request, context in
                try await self.rpRefreshSession(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: RPHandshakeService.Method.RPEndSession.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPEndSessionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<RPEndSessionResponse>(),
            handler: { request, context in
                try await self.rpEndSession(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHandshakeService.ServiceProtocol {
    public func rpInitiate(
        request: GRPCCore.StreamingServerRequest<RPInitiateRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RPInitiateResponse> {
        let response = try await self.rpInitiate(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func rpRefreshSession(
        request: GRPCCore.StreamingServerRequest<RPRefreshSessionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RPRefreshSessionResponse> {
        let response = try await self.rpRefreshSession(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func rpEndSession(
        request: GRPCCore.StreamingServerRequest<RPEndSessionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RPEndSessionResponse> {
        let response = try await self.rpEndSession(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHandshakeService.SimpleServiceProtocol {
    public func rpInitiate(
        request: GRPCCore.ServerRequest<RPInitiateRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<RPInitiateResponse> {
        return GRPCCore.ServerResponse<RPInitiateResponse>(
            message: try await self.rpInitiate(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func rpRefreshSession(
        request: GRPCCore.ServerRequest<RPRefreshSessionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<RPRefreshSessionResponse> {
        return GRPCCore.ServerResponse<RPRefreshSessionResponse>(
            message: try await self.rpRefreshSession(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func rpEndSession(
        request: GRPCCore.ServerRequest<RPEndSessionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<RPEndSessionResponse> {
        return GRPCCore.ServerResponse<RPEndSessionResponse>(
            message: try await self.rpEndSession(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: proto.renderprotocol.api.v1.RPHandshakeService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHandshakeService {
    /// Generated client protocol for the "proto.renderprotocol.api.v1.RPHandshakeService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "RPInitiate" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPInitiateRequest` message.
        ///   - serializer: A serializer for `RPInitiateRequest` messages.
        ///   - deserializer: A deserializer for `RPInitiateResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func rpInitiate<Result>(
            request: GRPCCore.ClientRequest<RPInitiateRequest>,
            serializer: some GRPCCore.MessageSerializer<RPInitiateRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPInitiateResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPInitiateResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RPRefreshSession" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPRefreshSessionRequest` message.
        ///   - serializer: A serializer for `RPRefreshSessionRequest` messages.
        ///   - deserializer: A deserializer for `RPRefreshSessionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func rpRefreshSession<Result>(
            request: GRPCCore.ClientRequest<RPRefreshSessionRequest>,
            serializer: some GRPCCore.MessageSerializer<RPRefreshSessionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPRefreshSessionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPRefreshSessionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RPEndSession" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPEndSessionRequest` message.
        ///   - serializer: A serializer for `RPEndSessionRequest` messages.
        ///   - deserializer: A deserializer for `RPEndSessionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func rpEndSession<Result>(
            request: GRPCCore.ClientRequest<RPEndSessionRequest>,
            serializer: some GRPCCore.MessageSerializer<RPEndSessionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPEndSessionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPEndSessionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "proto.renderprotocol.api.v1.RPHandshakeService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "RPInitiate" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPInitiateRequest` message.
        ///   - serializer: A serializer for `RPInitiateRequest` messages.
        ///   - deserializer: A deserializer for `RPInitiateResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func rpInitiate<Result>(
            request: GRPCCore.ClientRequest<RPInitiateRequest>,
            serializer: some GRPCCore.MessageSerializer<RPInitiateRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPInitiateResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPInitiateResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RPHandshakeService.Method.RPInitiate.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RPRefreshSession" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPRefreshSessionRequest` message.
        ///   - serializer: A serializer for `RPRefreshSessionRequest` messages.
        ///   - deserializer: A deserializer for `RPRefreshSessionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func rpRefreshSession<Result>(
            request: GRPCCore.ClientRequest<RPRefreshSessionRequest>,
            serializer: some GRPCCore.MessageSerializer<RPRefreshSessionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPRefreshSessionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPRefreshSessionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RPHandshakeService.Method.RPRefreshSession.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RPEndSession" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RPEndSessionRequest` message.
        ///   - serializer: A serializer for `RPEndSessionRequest` messages.
        ///   - deserializer: A deserializer for `RPEndSessionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func rpEndSession<Result>(
            request: GRPCCore.ClientRequest<RPEndSessionRequest>,
            serializer: some GRPCCore.MessageSerializer<RPEndSessionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RPEndSessionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPEndSessionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RPHandshakeService.Method.RPEndSession.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHandshakeService.ClientProtocol {
    /// Call the "RPInitiate" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `RPInitiateRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpInitiate<Result>(
        request: GRPCCore.ClientRequest<RPInitiateRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPInitiateResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.rpInitiate(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<RPInitiateRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPInitiateResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RPRefreshSession" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `RPRefreshSessionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpRefreshSession<Result>(
        request: GRPCCore.ClientRequest<RPRefreshSessionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPRefreshSessionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.rpRefreshSession(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<RPRefreshSessionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPRefreshSessionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RPEndSession" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `RPEndSessionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpEndSession<Result>(
        request: GRPCCore.ClientRequest<RPEndSessionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPEndSessionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.rpEndSession(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<RPEndSessionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<RPEndSessionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RPHandshakeService.ClientProtocol {
    /// Call the "RPInitiate" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpInitiate<Result>(
        _ message: RPInitiateRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPInitiateResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<RPInitiateRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.rpInitiate(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RPRefreshSession" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpRefreshSession<Result>(
        _ message: RPRefreshSessionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPRefreshSessionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<RPRefreshSessionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.rpRefreshSession(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RPEndSession" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func rpEndSession<Result>(
        _ message: RPEndSessionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<RPEndSessionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<RPEndSessionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.rpEndSession(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}