// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/ui/v1/rp_ui_alignment.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum RPAlignment: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case center // = 1
  case top // = 2
  case bottom // = 3
  case leading // = 4
  case trailing // = 5
  case topLeading // = 6
  case topTrailing // = 7
  case bottomLeading // = 8
  case bottomTrailing // = 9
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .center
    case 2: self = .top
    case 3: self = .bottom
    case 4: self = .leading
    case 5: self = .trailing
    case 6: self = .topLeading
    case 7: self = .topTrailing
    case 8: self = .bottomLeading
    case 9: self = .bottomTrailing
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .center: return 1
    case .top: return 2
    case .bottom: return 3
    case .leading: return 4
    case .trailing: return 5
    case .topLeading: return 6
    case .topTrailing: return 7
    case .bottomLeading: return 8
    case .bottomTrailing: return 9
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPAlignment] = [
    .unspecified,
    .center,
    .top,
    .bottom,
    .leading,
    .trailing,
    .topLeading,
    .topTrailing,
    .bottomLeading,
    .bottomTrailing,
  ]

}

public enum RPAxisAlignment: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case center // = 1
  case leading // = 2
  case trailing // = 3
  case spaceBetween // = 4
  case spaceEvenly // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .center
    case 2: self = .leading
    case 3: self = .trailing
    case 4: self = .spaceBetween
    case 5: self = .spaceEvenly
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .center: return 1
    case .leading: return 2
    case .trailing: return 3
    case .spaceBetween: return 4
    case .spaceEvenly: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPAxisAlignment] = [
    .unspecified,
    .center,
    .leading,
    .trailing,
    .spaceBetween,
    .spaceEvenly,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension RPAlignment: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_ALIGNMENT_UNSPECIFIED\0\u{1}RP_ALIGNMENT_CENTER\0\u{1}RP_ALIGNMENT_TOP\0\u{1}RP_ALIGNMENT_BOTTOM\0\u{1}RP_ALIGNMENT_LEADING\0\u{1}RP_ALIGNMENT_TRAILING\0\u{1}RP_ALIGNMENT_TOP_LEADING\0\u{1}RP_ALIGNMENT_TOP_TRAILING\0\u{1}RP_ALIGNMENT_BOTTOM_LEADING\0\u{1}RP_ALIGNMENT_BOTTOM_TRAILING\0")
}

extension RPAxisAlignment: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_AXIS_ALIGNMENT_UNSPECIFIED\0\u{1}RP_AXIS_ALIGNMENT_CENTER\0\u{1}RP_AXIS_ALIGNMENT_LEADING\0\u{1}RP_AXIS_ALIGNMENT_TRAILING\0\u{1}RP_AXIS_ALIGNMENT_SPACE_BETWEEN\0\u{1}RP_AXIS_ALIGNMENT_SPACE_EVENLY\0")
}
