// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/ui/v1/rp_ui_bottom_nav_bar.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct RPBottomNavBar: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var items: [RPBottomNavItem] = []

  public var selectedIndex: Int32 {
    get {_selectedIndex ?? 0}
    set {_selectedIndex = newValue}
  }
  /// Returns true if `selectedIndex` has been explicitly set.
  public var hasSelectedIndex: Bool {self._selectedIndex != nil}
  /// Clears the value of `selectedIndex`. Subsequent reads from it will return its default value.
  public mutating func clearSelectedIndex() {self._selectedIndex = nil}

  public var backgroundColor: RPColor {
    get {_backgroundColor ?? RPColor()}
    set {_backgroundColor = newValue}
  }
  /// Returns true if `backgroundColor` has been explicitly set.
  public var hasBackgroundColor: Bool {self._backgroundColor != nil}
  /// Clears the value of `backgroundColor`. Subsequent reads from it will return its default value.
  public mutating func clearBackgroundColor() {self._backgroundColor = nil}

  public var selectedColor: RPColor {
    get {_selectedColor ?? RPColor()}
    set {_selectedColor = newValue}
  }
  /// Returns true if `selectedColor` has been explicitly set.
  public var hasSelectedColor: Bool {self._selectedColor != nil}
  /// Clears the value of `selectedColor`. Subsequent reads from it will return its default value.
  public mutating func clearSelectedColor() {self._selectedColor = nil}

  public var unselectedColor: RPColor {
    get {_unselectedColor ?? RPColor()}
    set {_unselectedColor = newValue}
  }
  /// Returns true if `unselectedColor` has been explicitly set.
  public var hasUnselectedColor: Bool {self._unselectedColor != nil}
  /// Clears the value of `unselectedColor`. Subsequent reads from it will return its default value.
  public mutating func clearUnselectedColor() {self._unselectedColor = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _selectedIndex: Int32? = nil
  fileprivate var _backgroundColor: RPColor? = nil
  fileprivate var _selectedColor: RPColor? = nil
  fileprivate var _unselectedColor: RPColor? = nil
}

public struct RPBottomNavItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var icon: RPIcon {
    get {_icon ?? RPIcon()}
    set {_icon = newValue}
  }
  /// Returns true if `icon` has been explicitly set.
  public var hasIcon: Bool {self._icon != nil}
  /// Clears the value of `icon`. Subsequent reads from it will return its default value.
  public mutating func clearIcon() {self._icon = nil}

  public var label: String {
    get {_label ?? String()}
    set {_label = newValue}
  }
  /// Returns true if `label` has been explicitly set.
  public var hasLabel: Bool {self._label != nil}
  /// Clears the value of `label`. Subsequent reads from it will return its default value.
  public mutating func clearLabel() {self._label = nil}

  public var action: RPAction {
    get {_action ?? RPAction()}
    set {_action = newValue}
  }
  /// Returns true if `action` has been explicitly set.
  public var hasAction: Bool {self._action != nil}
  /// Clears the value of `action`. Subsequent reads from it will return its default value.
  public mutating func clearAction() {self._action = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _icon: RPIcon? = nil
  fileprivate var _label: String? = nil
  fileprivate var _action: RPAction? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto.renderprotocol.ui.v1"

extension RPBottomNavBar: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPBottomNavBar"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}items\0\u{3}selected_index\0\u{3}background_color\0\u{3}selected_color\0\u{3}unselected_color\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._selectedIndex) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._backgroundColor) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._selectedColor) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._unselectedColor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 1)
    }
    try { if let v = self._selectedIndex {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._backgroundColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._selectedColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._unselectedColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPBottomNavBar, rhs: RPBottomNavBar) -> Bool {
    if lhs.items != rhs.items {return false}
    if lhs._selectedIndex != rhs._selectedIndex {return false}
    if lhs._backgroundColor != rhs._backgroundColor {return false}
    if lhs._selectedColor != rhs._selectedColor {return false}
    if lhs._unselectedColor != rhs._unselectedColor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RPBottomNavItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPBottomNavItem"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}icon\0\u{1}label\0\u{1}action\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._icon) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._label) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._action) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._icon {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._label {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._action {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPBottomNavItem, rhs: RPBottomNavItem) -> Bool {
    if lhs._icon != rhs._icon {return false}
    if lhs._label != rhs._label {return false}
    if lhs._action != rhs._action {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
