// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/ui/v1/rp_ui_clip.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum RPClipType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case hardEdge // = 1
  case antiAlias // = 2
  case antiAliasWithSaveLayer // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .hardEdge
    case 2: self = .antiAlias
    case 3: self = .antiAliasWithSaveLayer
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .hardEdge: return 1
    case .antiAlias: return 2
    case .antiAliasWithSaveLayer: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPClipType] = [
    .unspecified,
    .hardEdge,
    .antiAlias,
    .antiAliasWithSaveLayer,
  ]

}

public struct RPClip: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var shape: RPClipShape {
    get {_shape ?? RPClipShape()}
    set {_shape = newValue}
  }
  /// Returns true if `shape` has been explicitly set.
  public var hasShape: Bool {self._shape != nil}
  /// Clears the value of `shape`. Subsequent reads from it will return its default value.
  public mutating func clearShape() {self._shape = nil}

  public var type: RPClipType = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _shape: RPClipShape? = nil
}

public struct RPClipShape: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: RPClipShape.OneOf_Value? = nil

  public var rectangle: RPShapeRectangle {
    get {
      if case .rectangle(let v)? = value {return v}
      return RPShapeRectangle()
    }
    set {value = .rectangle(newValue)}
  }

  public var circle: RPShapeCircle {
    get {
      if case .circle(let v)? = value {return v}
      return RPShapeCircle()
    }
    set {value = .circle(newValue)}
  }

  public var ellipse: RPShapeEllipse {
    get {
      if case .ellipse(let v)? = value {return v}
      return RPShapeEllipse()
    }
    set {value = .ellipse(newValue)}
  }

  public var capsule: RPShapeCapsule {
    get {
      if case .capsule(let v)? = value {return v}
      return RPShapeCapsule()
    }
    set {value = .capsule(newValue)}
  }

  public var roundedRectangle: RPShapeRoundedRectangle {
    get {
      if case .roundedRectangle(let v)? = value {return v}
      return RPShapeRoundedRectangle()
    }
    set {value = .roundedRectangle(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Value: Equatable, Sendable {
    case rectangle(RPShapeRectangle)
    case circle(RPShapeCircle)
    case ellipse(RPShapeEllipse)
    case capsule(RPShapeCapsule)
    case roundedRectangle(RPShapeRoundedRectangle)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto.renderprotocol.ui.v1"

extension RPClipType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_CLIP_TYPE_UNSPECIFIED\0\u{1}RP_CLIP_TYPE_HARD_EDGE\0\u{1}RP_CLIP_TYPE_ANTI_ALIAS\0\u{1}RP_CLIP_TYPE_ANTI_ALIAS_WITH_SAVE_LAYER\0")
}

extension RPClip: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPClip"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}shape\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._shape) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._shape {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.type != .unspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPClip, rhs: RPClip) -> Bool {
    if lhs._shape != rhs._shape {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RPClipShape: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPClipShape"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}rectangle\0\u{1}circle\0\u{1}ellipse\0\u{1}capsule\0\u{3}rounded_rectangle\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: RPShapeRectangle?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .rectangle(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .rectangle(v)
        }
      }()
      case 2: try {
        var v: RPShapeCircle?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .circle(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .circle(v)
        }
      }()
      case 3: try {
        var v: RPShapeEllipse?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .ellipse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .ellipse(v)
        }
      }()
      case 4: try {
        var v: RPShapeCapsule?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .capsule(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .capsule(v)
        }
      }()
      case 5: try {
        var v: RPShapeRoundedRectangle?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .roundedRectangle(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .roundedRectangle(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .rectangle?: try {
      guard case .rectangle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .circle?: try {
      guard case .circle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .ellipse?: try {
      guard case .ellipse(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .capsule?: try {
      guard case .capsule(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .roundedRectangle?: try {
      guard case .roundedRectangle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPClipShape, rhs: RPClipShape) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
