// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/ui/v1/rp_ui_core_support.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum RPAlignment: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case center // = 1
  case top // = 2
  case bottom // = 3
  case leading // = 4
  case trailing // = 5
  case topLeading // = 6
  case topTrailing // = 7
  case bottomLeading // = 8
  case bottomTrailing // = 9
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .center
    case 2: self = .top
    case 3: self = .bottom
    case 4: self = .leading
    case 5: self = .trailing
    case 6: self = .topLeading
    case 7: self = .topTrailing
    case 8: self = .bottomLeading
    case 9: self = .bottomTrailing
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .center: return 1
    case .top: return 2
    case .bottom: return 3
    case .leading: return 4
    case .trailing: return 5
    case .topLeading: return 6
    case .topTrailing: return 7
    case .bottomLeading: return 8
    case .bottomTrailing: return 9
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPAlignment] = [
    .unspecified,
    .center,
    .top,
    .bottom,
    .leading,
    .trailing,
    .topLeading,
    .topTrailing,
    .bottomLeading,
    .bottomTrailing,
  ]

}

public nonisolated enum RPAxisAlignment: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case center // = 1
  case leading // = 2
  case trailing // = 3
  case spaceBetween // = 4
  case spaceEvenly // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .center
    case 2: self = .leading
    case 3: self = .trailing
    case 4: self = .spaceBetween
    case 5: self = .spaceEvenly
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .center: return 1
    case .leading: return 2
    case .trailing: return 3
    case .spaceBetween: return 4
    case .spaceEvenly: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPAxisAlignment] = [
    .unspecified,
    .center,
    .leading,
    .trailing,
    .spaceBetween,
    .spaceEvenly,
  ]

}

public nonisolated enum RPClipType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case hardEdge // = 1
  case antiAlias // = 2
  case antiAliasWithSaveLayer // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .hardEdge
    case 2: self = .antiAlias
    case 3: self = .antiAliasWithSaveLayer
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .hardEdge: return 1
    case .antiAlias: return 2
    case .antiAliasWithSaveLayer: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPClipType] = [
    .unspecified,
    .hardEdge,
    .antiAlias,
    .antiAliasWithSaveLayer,
  ]

}

public nonisolated enum RPAxis: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case horizontal // = 1
  case vertical // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .horizontal
    case 2: self = .vertical
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .horizontal: return 1
    case .vertical: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPAxis] = [
    .unspecified,
    .horizontal,
    .vertical,
  ]

}

public nonisolated enum RPCrossAxisAlignment: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case start // = 1
  case center // = 2
  case end // = 3
  case stretch // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .start
    case 2: self = .center
    case 3: self = .end
    case 4: self = .stretch
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .start: return 1
    case .center: return 2
    case .end: return 3
    case .stretch: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPCrossAxisAlignment] = [
    .unspecified,
    .start,
    .center,
    .end,
    .stretch,
  ]

}

public nonisolated enum RPMainAxisSize: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case min // = 1
  case max // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .min
    case 2: self = .max
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .min: return 1
    case .max: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPMainAxisSize] = [
    .unspecified,
    .min,
    .max,
  ]

}

public nonisolated enum RPButtonStyle: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case primary // = 1
  case secondary // = 2
  case text // = 3
  case outlined // = 4
  case destructive // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .primary
    case 2: self = .secondary
    case 3: self = .text
    case 4: self = .outlined
    case 5: self = .destructive
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .primary: return 1
    case .secondary: return 2
    case .text: return 3
    case .outlined: return 4
    case .destructive: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPButtonStyle] = [
    .unspecified,
    .primary,
    .secondary,
    .text,
    .outlined,
    .destructive,
  ]

}

public nonisolated struct RPSymmetricPadding: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var vertical: Float = 0

  public var horizontal: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct RPExplicitPadding: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var top: Float = 0

  public var bottom: Float = 0

  public var left: Float = 0

  public var right: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct RPClipShape: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: RPClipShape.OneOf_Value? = nil

  public var rectangle: RPShapeRectangle {
    get {
      if case .rectangle(let v)? = value {return v}
      return RPShapeRectangle()
    }
    set {value = .rectangle(newValue)}
  }

  public var circle: RPShapeCircle {
    get {
      if case .circle(let v)? = value {return v}
      return RPShapeCircle()
    }
    set {value = .circle(newValue)}
  }

  public var ellipse: RPShapeEllipse {
    get {
      if case .ellipse(let v)? = value {return v}
      return RPShapeEllipse()
    }
    set {value = .ellipse(newValue)}
  }

  public var capsule: RPShapeCapsule {
    get {
      if case .capsule(let v)? = value {return v}
      return RPShapeCapsule()
    }
    set {value = .capsule(newValue)}
  }

  public var roundedRectangle: RPShapeRoundedRectangle {
    get {
      if case .roundedRectangle(let v)? = value {return v}
      return RPShapeRoundedRectangle()
    }
    set {value = .roundedRectangle(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Value: Equatable, Sendable {
    case rectangle(RPShapeRectangle)
    case circle(RPShapeCircle)
    case ellipse(RPShapeEllipse)
    case capsule(RPShapeCapsule)
    case roundedRectangle(RPShapeRoundedRectangle)

  }

  public init() {}
}

public nonisolated struct RPSize: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var width: Float = 0

  public var height: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct RPEdgeInsets: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var top: Float = 0

  public var bottom: Float = 0

  public var leading: Float = 0

  public var trailing: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct RPGridLayout: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: RPGridLayout.OneOf_Value? = nil

  public var fixed: RPFixedGrid {
    get {
      if case .fixed(let v)? = value {return v}
      return RPFixedGrid()
    }
    set {value = .fixed(newValue)}
  }

  public var adaptive: RPAdaptiveGrid {
    get {
      if case .adaptive(let v)? = value {return v}
      return RPAdaptiveGrid()
    }
    set {value = .adaptive(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Value: Equatable, Sendable {
    case fixed(RPFixedGrid)
    case adaptive(RPAdaptiveGrid)

  }

  public init() {}
}

public nonisolated struct RPFixedGrid: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var count: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct RPAdaptiveGrid: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var minItemWidth: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "proto.renderprotocol.ui.v1"

nonisolated extension RPAlignment: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_ALIGNMENT_UNSPECIFIED\0\u{1}RP_ALIGNMENT_CENTER\0\u{1}RP_ALIGNMENT_TOP\0\u{1}RP_ALIGNMENT_BOTTOM\0\u{1}RP_ALIGNMENT_LEADING\0\u{1}RP_ALIGNMENT_TRAILING\0\u{1}RP_ALIGNMENT_TOP_LEADING\0\u{1}RP_ALIGNMENT_TOP_TRAILING\0\u{1}RP_ALIGNMENT_BOTTOM_LEADING\0\u{1}RP_ALIGNMENT_BOTTOM_TRAILING\0")
}

nonisolated extension RPAxisAlignment: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_AXIS_ALIGNMENT_UNSPECIFIED\0\u{1}RP_AXIS_ALIGNMENT_CENTER\0\u{1}RP_AXIS_ALIGNMENT_LEADING\0\u{1}RP_AXIS_ALIGNMENT_TRAILING\0\u{1}RP_AXIS_ALIGNMENT_SPACE_BETWEEN\0\u{1}RP_AXIS_ALIGNMENT_SPACE_EVENLY\0")
}

nonisolated extension RPClipType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_CLIP_TYPE_UNSPECIFIED\0\u{1}RP_CLIP_TYPE_HARD_EDGE\0\u{1}RP_CLIP_TYPE_ANTI_ALIAS\0\u{1}RP_CLIP_TYPE_ANTI_ALIAS_WITH_SAVE_LAYER\0")
}

nonisolated extension RPAxis: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_AXIS_UNSPECIFIED\0\u{1}RP_AXIS_HORIZONTAL\0\u{1}RP_AXIS_VERTICAL\0")
}

nonisolated extension RPCrossAxisAlignment: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_CROSS_AXIS_ALIGNMENT_UNSPECIFIED\0\u{1}RP_CROSS_AXIS_ALIGNMENT_START\0\u{1}RP_CROSS_AXIS_ALIGNMENT_CENTER\0\u{1}RP_CROSS_AXIS_ALIGNMENT_END\0\u{1}RP_CROSS_AXIS_ALIGNMENT_STRETCH\0")
}

nonisolated extension RPMainAxisSize: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_MAIN_AXIS_SIZE_UNSPECIFIED\0\u{1}RP_MAIN_AXIS_SIZE_MIN\0\u{1}RP_MAIN_AXIS_SIZE_MAX\0")
}

nonisolated extension RPButtonStyle: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_BUTTON_STYLE_UNSPECIFIED\0\u{1}RP_BUTTON_STYLE_PRIMARY\0\u{1}RP_BUTTON_STYLE_SECONDARY\0\u{1}RP_BUTTON_STYLE_TEXT\0\u{1}RP_BUTTON_STYLE_OUTLINED\0\u{1}RP_BUTTON_STYLE_DESTRUCTIVE\0")
}

nonisolated extension RPSymmetricPadding: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPSymmetricPadding"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}vertical\0\u{1}horizontal\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.vertical) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.horizontal) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.vertical.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.vertical, fieldNumber: 1)
    }
    if self.horizontal.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.horizontal, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPSymmetricPadding, rhs: RPSymmetricPadding) -> Bool {
    if lhs.vertical != rhs.vertical {return false}
    if lhs.horizontal != rhs.horizontal {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RPExplicitPadding: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPExplicitPadding"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}top\0\u{1}bottom\0\u{1}left\0\u{1}right\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.top) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.bottom) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.left) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.right) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.top.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.top, fieldNumber: 1)
    }
    if self.bottom.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.bottom, fieldNumber: 2)
    }
    if self.left.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.left, fieldNumber: 3)
    }
    if self.right.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.right, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPExplicitPadding, rhs: RPExplicitPadding) -> Bool {
    if lhs.top != rhs.top {return false}
    if lhs.bottom != rhs.bottom {return false}
    if lhs.left != rhs.left {return false}
    if lhs.right != rhs.right {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RPClipShape: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPClipShape"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}rectangle\0\u{1}circle\0\u{1}ellipse\0\u{1}capsule\0\u{3}rounded_rectangle\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: RPShapeRectangle?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .rectangle(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .rectangle(v)
        }
      }()
      case 2: try {
        var v: RPShapeCircle?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .circle(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .circle(v)
        }
      }()
      case 3: try {
        var v: RPShapeEllipse?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .ellipse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .ellipse(v)
        }
      }()
      case 4: try {
        var v: RPShapeCapsule?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .capsule(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .capsule(v)
        }
      }()
      case 5: try {
        var v: RPShapeRoundedRectangle?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .roundedRectangle(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .roundedRectangle(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .rectangle?: try {
      guard case .rectangle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .circle?: try {
      guard case .circle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .ellipse?: try {
      guard case .ellipse(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .capsule?: try {
      guard case .capsule(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .roundedRectangle?: try {
      guard case .roundedRectangle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPClipShape, rhs: RPClipShape) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RPSize: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPSize"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.width) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.width.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.width, fieldNumber: 1)
    }
    if self.height.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.height, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPSize, rhs: RPSize) -> Bool {
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RPEdgeInsets: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPEdgeInsets"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}top\0\u{1}bottom\0\u{1}leading\0\u{1}trailing\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.top) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.bottom) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.leading) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.trailing) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.top.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.top, fieldNumber: 1)
    }
    if self.bottom.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.bottom, fieldNumber: 2)
    }
    if self.leading.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.leading, fieldNumber: 3)
    }
    if self.trailing.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.trailing, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPEdgeInsets, rhs: RPEdgeInsets) -> Bool {
    if lhs.top != rhs.top {return false}
    if lhs.bottom != rhs.bottom {return false}
    if lhs.leading != rhs.leading {return false}
    if lhs.trailing != rhs.trailing {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RPGridLayout: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPGridLayout"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fixed\0\u{1}adaptive\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: RPFixedGrid?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .fixed(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .fixed(v)
        }
      }()
      case 2: try {
        var v: RPAdaptiveGrid?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .adaptive(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .adaptive(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .fixed?: try {
      guard case .fixed(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .adaptive?: try {
      guard case .adaptive(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPGridLayout, rhs: RPGridLayout) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RPFixedGrid: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPFixedGrid"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.count) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.count != 0 {
      try visitor.visitSingularInt32Field(value: self.count, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPFixedGrid, rhs: RPFixedGrid) -> Bool {
    if lhs.count != rhs.count {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension RPAdaptiveGrid: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPAdaptiveGrid"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}min_item_width\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.minItemWidth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.minItemWidth.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.minItemWidth, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPAdaptiveGrid, rhs: RPAdaptiveGrid) -> Bool {
    if lhs.minItemWidth != rhs.minItemWidth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
