// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/ui/v1/rp_ui_progress_indicator.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum RPProgressIndicatorType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case circular // = 1
  case linear // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .circular
    case 2: self = .linear
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .circular: return 1
    case .linear: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPProgressIndicatorType] = [
    .unspecified,
    .circular,
    .linear,
  ]

}

public struct RPProgressIndicator: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: RPProgressIndicatorType = .unspecified

  public var value: Float {
    get {_value ?? 0}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var color: RPColor {
    get {_color ?? RPColor()}
    set {_color = newValue}
  }
  /// Returns true if `color` has been explicitly set.
  public var hasColor: Bool {self._color != nil}
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  public mutating func clearColor() {self._color = nil}

  public var trackColor: RPColor {
    get {_trackColor ?? RPColor()}
    set {_trackColor = newValue}
  }
  /// Returns true if `trackColor` has been explicitly set.
  public var hasTrackColor: Bool {self._trackColor != nil}
  /// Clears the value of `trackColor`. Subsequent reads from it will return its default value.
  public mutating func clearTrackColor() {self._trackColor = nil}

  public var strokeWidth: Float {
    get {_strokeWidth ?? 0}
    set {_strokeWidth = newValue}
  }
  /// Returns true if `strokeWidth` has been explicitly set.
  public var hasStrokeWidth: Bool {self._strokeWidth != nil}
  /// Clears the value of `strokeWidth`. Subsequent reads from it will return its default value.
  public mutating func clearStrokeWidth() {self._strokeWidth = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _value: Float? = nil
  fileprivate var _color: RPColor? = nil
  fileprivate var _trackColor: RPColor? = nil
  fileprivate var _strokeWidth: Float? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto.renderprotocol.ui.v1"

extension RPProgressIndicatorType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_PROGRESS_INDICATOR_TYPE_UNSPECIFIED\0\u{1}RP_PROGRESS_INDICATOR_TYPE_CIRCULAR\0\u{1}RP_PROGRESS_INDICATOR_TYPE_LINEAR\0")
}

extension RPProgressIndicator: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPProgressIndicator"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}value\0\u{1}color\0\u{3}track_color\0\u{3}stroke_width\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self._value) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._color) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._trackColor) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self._strokeWidth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.type != .unspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    try { if let v = self._value {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._color {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._trackColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._strokeWidth {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPProgressIndicator, rhs: RPProgressIndicator) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs._value != rhs._value {return false}
    if lhs._color != rhs._color {return false}
    if lhs._trackColor != rhs._trackColor {return false}
    if lhs._strokeWidth != rhs._strokeWidth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
