// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/ui/v1/rp_ui_text_field.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum RPKeyboardType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case `default` // = 1
  case email // = 2
  case number // = 3
  case phone // = 4
  case url // = 5
  case decimal // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .default
    case 2: self = .email
    case 3: self = .number
    case 4: self = .phone
    case 5: self = .url
    case 6: self = .decimal
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .default: return 1
    case .email: return 2
    case .number: return 3
    case .phone: return 4
    case .url: return 5
    case .decimal: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [RPKeyboardType] = [
    .unspecified,
    .default,
    .email,
    .number,
    .phone,
    .url,
    .decimal,
  ]

}

public struct RPTextField: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var fieldID: String {
    get {_storage._fieldID}
    set {_uniqueStorage()._fieldID = newValue}
  }

  public var placeholder: String {
    get {_storage._placeholder ?? String()}
    set {_uniqueStorage()._placeholder = newValue}
  }
  /// Returns true if `placeholder` has been explicitly set.
  public var hasPlaceholder: Bool {_storage._placeholder != nil}
  /// Clears the value of `placeholder`. Subsequent reads from it will return its default value.
  public mutating func clearPlaceholder() {_uniqueStorage()._placeholder = nil}

  public var initialValue: String {
    get {_storage._initialValue ?? String()}
    set {_uniqueStorage()._initialValue = newValue}
  }
  /// Returns true if `initialValue` has been explicitly set.
  public var hasInitialValue: Bool {_storage._initialValue != nil}
  /// Clears the value of `initialValue`. Subsequent reads from it will return its default value.
  public mutating func clearInitialValue() {_uniqueStorage()._initialValue = nil}

  public var keyboardType: RPKeyboardType {
    get {_storage._keyboardType}
    set {_uniqueStorage()._keyboardType = newValue}
  }

  public var secureEntry: Bool {
    get {_storage._secureEntry}
    set {_uniqueStorage()._secureEntry = newValue}
  }

  public var maxLength: Int32 {
    get {_storage._maxLength ?? 0}
    set {_uniqueStorage()._maxLength = newValue}
  }
  /// Returns true if `maxLength` has been explicitly set.
  public var hasMaxLength: Bool {_storage._maxLength != nil}
  /// Clears the value of `maxLength`. Subsequent reads from it will return its default value.
  public mutating func clearMaxLength() {_uniqueStorage()._maxLength = nil}

  public var textStyle: RPTextStyle {
    get {_storage._textStyle ?? RPTextStyle()}
    set {_uniqueStorage()._textStyle = newValue}
  }
  /// Returns true if `textStyle` has been explicitly set.
  public var hasTextStyle: Bool {_storage._textStyle != nil}
  /// Clears the value of `textStyle`. Subsequent reads from it will return its default value.
  public mutating func clearTextStyle() {_uniqueStorage()._textStyle = nil}

  public var enabled: Bool {
    get {_storage._enabled}
    set {_uniqueStorage()._enabled = newValue}
  }

  public var onSubmit: RPAction {
    get {_storage._onSubmit ?? RPAction()}
    set {_uniqueStorage()._onSubmit = newValue}
  }
  /// Returns true if `onSubmit` has been explicitly set.
  public var hasOnSubmit: Bool {_storage._onSubmit != nil}
  /// Clears the value of `onSubmit`. Subsequent reads from it will return its default value.
  public mutating func clearOnSubmit() {_uniqueStorage()._onSubmit = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto.renderprotocol.ui.v1"

extension RPKeyboardType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RP_KEYBOARD_TYPE_UNSPECIFIED\0\u{1}RP_KEYBOARD_TYPE_DEFAULT\0\u{1}RP_KEYBOARD_TYPE_EMAIL\0\u{1}RP_KEYBOARD_TYPE_NUMBER\0\u{1}RP_KEYBOARD_TYPE_PHONE\0\u{1}RP_KEYBOARD_TYPE_URL\0\u{1}RP_KEYBOARD_TYPE_DECIMAL\0")
}

extension RPTextField: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPTextField"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}field_id\0\u{1}placeholder\0\u{3}initial_value\0\u{3}keyboard_type\0\u{3}secure_entry\0\u{3}max_length\0\u{3}text_style\0\u{1}enabled\0\u{3}on_submit\0")

  fileprivate class _StorageClass {
    var _fieldID: String = String()
    var _placeholder: String? = nil
    var _initialValue: String? = nil
    var _keyboardType: RPKeyboardType = .unspecified
    var _secureEntry: Bool = false
    var _maxLength: Int32? = nil
    var _textStyle: RPTextStyle? = nil
    var _enabled: Bool = false
    var _onSubmit: RPAction? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _fieldID = source._fieldID
      _placeholder = source._placeholder
      _initialValue = source._initialValue
      _keyboardType = source._keyboardType
      _secureEntry = source._secureEntry
      _maxLength = source._maxLength
      _textStyle = source._textStyle
      _enabled = source._enabled
      _onSubmit = source._onSubmit
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._fieldID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._placeholder) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._initialValue) }()
        case 4: try { try decoder.decodeSingularEnumField(value: &_storage._keyboardType) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._secureEntry) }()
        case 6: try { try decoder.decodeSingularInt32Field(value: &_storage._maxLength) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._textStyle) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._enabled) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._onSubmit) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._fieldID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fieldID, fieldNumber: 1)
      }
      try { if let v = _storage._placeholder {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._initialValue {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      if _storage._keyboardType != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._keyboardType, fieldNumber: 4)
      }
      if _storage._secureEntry != false {
        try visitor.visitSingularBoolField(value: _storage._secureEntry, fieldNumber: 5)
      }
      try { if let v = _storage._maxLength {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._textStyle {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if _storage._enabled != false {
        try visitor.visitSingularBoolField(value: _storage._enabled, fieldNumber: 8)
      }
      try { if let v = _storage._onSubmit {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPTextField, rhs: RPTextField) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._fieldID != rhs_storage._fieldID {return false}
        if _storage._placeholder != rhs_storage._placeholder {return false}
        if _storage._initialValue != rhs_storage._initialValue {return false}
        if _storage._keyboardType != rhs_storage._keyboardType {return false}
        if _storage._secureEntry != rhs_storage._secureEntry {return false}
        if _storage._maxLength != rhs_storage._maxLength {return false}
        if _storage._textStyle != rhs_storage._textStyle {return false}
        if _storage._enabled != rhs_storage._enabled {return false}
        if _storage._onSubmit != rhs_storage._onSubmit {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
