// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/renderprotocol/ui/v1/rp_ui_modifier.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct RPModifier: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: RPModifier.OneOf_Value? = nil

  public var border: RPBorder {
    get {
      if case .border(let v)? = value {return v}
      return RPBorder()
    }
    set {value = .border(newValue)}
  }

  public var padding: RPPadding {
    get {
      if case .padding(let v)? = value {return v}
      return RPPadding()
    }
    set {value = .padding(newValue)}
  }

  public var backgroundColor: RPColor {
    get {
      if case .backgroundColor(let v)? = value {return v}
      return RPColor()
    }
    set {value = .backgroundColor(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Value: Equatable, Sendable {
    case border(RPBorder)
    case padding(RPPadding)
    case backgroundColor(RPColor)

  }

  public init() {}
}

public struct RPPadding: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var top: Float = 0

  public var bottom: Float = 0

  public var left: Float = 0

  public var right: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct RPMargin: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var top: Float = 0

  public var bottom: Float = 0

  public var left: Float = 0

  public var right: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct RPBorder: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var width: Float = 0

  public var radius: Float = 0

  public var color: RPColor {
    get {return _color ?? RPColor()}
    set {_color = newValue}
  }
  /// Returns true if `color` has been explicitly set.
  public var hasColor: Bool {return self._color != nil}
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  public mutating func clearColor() {self._color = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _color: RPColor? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto.renderprotocol.ui.v1"

extension RPModifier: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPModifier"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}border\0\u{1}padding\0\u{3}background_color\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: RPBorder?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .border(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .border(v)
        }
      }()
      case 2: try {
        var v: RPPadding?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .padding(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .padding(v)
        }
      }()
      case 3: try {
        var v: RPColor?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .backgroundColor(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .backgroundColor(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .border?: try {
      guard case .border(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .padding?: try {
      guard case .padding(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .backgroundColor?: try {
      guard case .backgroundColor(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPModifier, rhs: RPModifier) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RPPadding: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPPadding"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}top\0\u{1}bottom\0\u{1}left\0\u{1}right\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.top) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.bottom) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.left) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.right) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.top.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.top, fieldNumber: 1)
    }
    if self.bottom.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.bottom, fieldNumber: 2)
    }
    if self.left.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.left, fieldNumber: 3)
    }
    if self.right.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.right, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPPadding, rhs: RPPadding) -> Bool {
    if lhs.top != rhs.top {return false}
    if lhs.bottom != rhs.bottom {return false}
    if lhs.left != rhs.left {return false}
    if lhs.right != rhs.right {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RPMargin: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPMargin"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}top\0\u{1}bottom\0\u{1}left\0\u{1}right\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.top) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.bottom) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.left) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.right) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.top.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.top, fieldNumber: 1)
    }
    if self.bottom.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.bottom, fieldNumber: 2)
    }
    if self.left.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.left, fieldNumber: 3)
    }
    if self.right.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.right, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPMargin, rhs: RPMargin) -> Bool {
    if lhs.top != rhs.top {return false}
    if lhs.bottom != rhs.bottom {return false}
    if lhs.left != rhs.left {return false}
    if lhs.right != rhs.right {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RPBorder: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RPBorder"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}width\0\u{1}radius\0\u{1}color\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.width) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.radius) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._color) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.width.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.width, fieldNumber: 1)
    }
    if self.radius.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.radius, fieldNumber: 2)
    }
    try { if let v = self._color {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RPBorder, rhs: RPBorder) -> Bool {
    if lhs.width != rhs.width {return false}
    if lhs.radius != rhs.radius {return false}
    if lhs._color != rhs._color {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
